### ISSUE TITLE
Add 2019 compatible version to Market Place

### ISSUE THREAD

**Issue by ivanxpetrov** [saravanaj/HideLightbulbMargin#2]
Hello,

thanks for creating the extension.
From the latest commit, it seems that it should be compatible with 2019.
For a variety of possible reasons, I cannot seem to be able to compile the source in VS 2019 Community.

Could you update the version in the Marketplace to the one with 2019 compatibility.

**Comment by saravanaj** [comment]
Hello, there are a few issues with disabling the lightbulb margin as it disables the "quick actions" feature completely. 

I am trying to see if the margin can be disabled while keeping the "quick actions" feature. 
Till then it is not recommended to use this extension.

I have anyway published the new version to the marketplace. Feel free to use it if you are ok with the issues.
